apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: lab-python-tempo-python-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lab-python-tempo-python-frontend
  template:
    metadata:
      labels:
        app: lab-python-tempo-python-frontend
    spec:
      containers:
        - name: lab-python-tempo-python-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
