global:
  clusterDomain: "cluster.local"
gateway:
  enabled: true
traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
distributor:
  config:
    log_received_spans:
      enabled: true
    log_discarded_spans:
      enabled: true
